    <section class="m-14 ">
        <!--Page calendrier-->
        <h1 class="text-5xl font-bold">
            Calendrier
        </h1>
        <div class="flex">
            <div class="w-full shrink-0">
                <!--filters-->
                <form class="flex items-center">
                    <div>
                        <div class="flex gap-2 items-center"> <i class="fa-solid fa-graduation-cap"></i>
                            <p class="flex gap-2">
                                Voir par
                            </p>
                        </div>

                        <select name="type" id="type" onchange="submitForm()">
                            <option value="class">Classe</option>
                            <option value="teacher">Formateurs</option>
                        </select>
                    </div>
                    <div>
                        <div class="flex gap-2 items-center"><i class="fa-solid fa-sliders"></i>
                            <p>Filtres</p>
                        </div>

                        <select name="grade" onchange="submitForm()">
                            <option value="class">B3</option>
                            <option value="teacher">M2 - GOOFY</option>
                        </select>
                        <select name="class" onchange="submitForm()">
                            <option value="class">DEV</option>
                            <option value="teacher">M2 - GOOFY</option>
                        </select>
                        <select name="session" onchange="submitForm()">
                            <option value="class">2024/2025</option>
                            <option value="teacher">2025/2026</option>
                        </select>
                    </div>
                    <button
                      class="text-white bg-beige-700 hover:bg-beige-800 focus:ring-4 focus:ring-beige-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-beige-600 dark:hover:bg-beige-700 focus:outline-none dark:focus:ring-beige-800"
                    >mettre à jour</button>
                </form>
                <!--fin filters-->

                <div class="flex gap-8">
                    <!--Calendrier-->
                    <main class="p-5 bg-beige-100 rounded-lg flex flex-col gap-5 max-w-[1369px] max-w-[75%]">
                        <h2 class="flex gap-2">
                            <i class="fa-solid fa-calendar-days"></i>
                            Calendrier B3 - DEV - 2024/2025
                        </h2>
                        <div id="calendar" class="bg-white rounded-sm">
                            <?php echo $calendrierHtml; ?>
                        </div>
                    </main>
                    <!--Fin Calendrier-->
                    <aside class="w-full">
                        <div class="w-full bg-beige-100 p-5 rounded-lg sticky top-8">
                            <h2>Modules</h2>
                            <div>
                                <?php if (count($modules) === 0): ?>
                                  aucun modules ajouté pour l'instant
                                <?php else: ?>
                                  <?php for (
                                    $i = 0;
                                    $i < count($modules);
                                    $i++
                                  ): ?>
                                      <div
                                          id="<?= $modules[$i]["id"] ?>"
                                          draggable="true"
                                          ondragstart="drag(event)"
                                          class="bg-[<?= $modules[$i][
                                            "color"
                                          ] ?>] rounded-lg mb-4 py-2 px-5 relative">

                                          <h3 class="text-xl font-semibold"><?= $modules[
                                            $i
                                          ]["nom"] ?> </h3>
                                          <?php
                                          $allocatedDuration = round(
                                            floatval(
                                              $modules[$i]["alocatedduration"]
                                            ),
                                            1
                                          );
                                          $duration = round(
                                            floatval($modules[$i]["duration"]),
                                            1
                                          );
                                          ?>
                                          <p><?= $allocatedDuration ?>
                                            heures allouées /
                                            <?= $modules[$i]["duration"] ?>
                                            heures
                                              <?php if (
                                                $allocatedDuration > $duration
                                              ): ?>
                                                  <span class="absolute -top-3 -right-3 text-red-500 bg-white rounded-lg p-2 w-10 h-10 flex justify-center items-center border-2 border-black">
                                                      <i class="fa-solid fa-triangle-exclamation fa-lg"></i>
                                                  </span>
                                              <?php endif; ?>
                                          </p>
                                      </div>
                                  <?php endfor; ?>
                                <?php endif; ?>
                            </div>
                        </div>
                    </aside>
                </div>
            </div>

        </div>
        <!--fin page calendrier-->
    </section>
    </body>

    </html>
