<div>
  <div class="flex gap-4 p-4">
    <section class="p-6 max-w-[1369px] w-full">
      <h1 class="text-2xl font-bold mb-4">Gestion des Classes et Sessions</h1>

      <!-- Section Classes -->
      <div class="mb-8">
        <div class="flex justify-between items-center mb-4">
          <h2 class="text-xl font-semibold">Classes</h2>
        </div>
        <!-- Liste des classes -->
        <div class="flex flex-col gap-4">
          <?php if (empty($classes)): ?>
            <p class="text-gray-500 italic">Aucune classe disponible</p>
          <?php else: ?>
            <?php foreach ($classes as $class): ?>
              <div class="p-4 shadow rounded-lg border border-gray-300" data-id="<?= htmlentities($class["id"]) ?>">
                <div class="flex gap-4 items-center">
                  <div class="flex-1 text-xl font-semibold"><?= htmlentities($class["nom"]) ?></div>
                  <div class="flex-1 text-gray-600">Grade ID: <?= htmlentities($class["id_grade"]) ?></div>

                  <form method="POST">
                    <input name="_method" type="hidden" value="delete_class">
                    <input name="class-id" type="hidden" value="<?= htmlentities($class["id"]) ?>">
                    <button class="flex w-10 h-10 rounded-[100%] items-center justify-center hover:bg-red-200 group">
                      <i class="fa-solid fa-trash group-hover:text-red-500"></i>
                    </button>
                  </form>
                </div>
              </div>
            <?php endforeach; ?>
          <?php endif; ?>
        </div>
      </div>
    </section>
    <section class="w-full max-w-[400px] sticky top-8">
      <h2 class="text-xl font-bold mt-8 mb-4">Ajouter une classe</h2>
      <form
        action="<?= $this->baseUrl . "classes-sessions" ?>"
        method="POST"
        class="p-4 bg-white shadow rounded-lg border border-gray-300 flex flex-col gap-4">
        <input name="_method" type="hidden" value="post"></input>
        <!-- Nom Input -->
        <div>
          <label for="nom" class="block text-sm font-medium text-gray-700">Nom</label>
          <input type="text" id="nom" name="nom" class="p-3 border border-gray-300 mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500" required>
        </div>
        <!-- Submit Button -->
        <div>
          <button
            type="submit"
            class="w-full bg-gray-950 text-white py-2 px-4 rounded-md hover:bg-gray-800">Ajouter</button>
        </div>
      </form>
    </section>
  </div>
  <div class="flex gap-4 p-4">
    <section class="p-6 max-w-[1369px] w-full">
      <!-- Section Sessions -->
      <div>
        <div class="flex justify-between items-center mb-4">
          <h2 class="text-xl font-semibold">Sessions</h2>
        </div>

        <!-- Liste des sessions -->
        <div class="flex flex-col gap-4">
          <?php if (empty($sessions)): ?>
            <p class="text-gray-500 italic">Aucune session disponible</p>
          <?php else: ?>
            <?php foreach ($sessions as $session): ?>
              <div class="p-4 shadow rounded-lg border border-gray-300" data-id="<?= htmlentities($session["id"]) ?>">
                <div class="flex gap-4 items-center">
                  <div class="flex-1 text-xl font-semibold"><?= htmlentities($session["name"]) ?></div>
                  <div class="flex-1 text-gray-600">
                    <?php if (htmlentities($session["is_active"]) == "1"): ?>
                      Session en cours
                      <i class="fa-solid fa-circle-check text-green-500"></i>
                    <?php else: ?>
                      Session innactive
                      <i class="fa-solid fa-xmark"></i>
                    <?php endif; ?>
                  </div>

                  <form method="POST">
                    <input name="_method" type="hidden" value="delete_session">
                    <input name="session-id" type="hidden" value="<?= htmlentities($session["id"]) ?>">
                    <button class="flex w-10 h-10 rounded-[100%] items-center justify-center hover:bg-red-200 group">
                      <i class="fa-solid fa-trash group-hover:text-red-500"></i>
                    </button>
                  </form>
                </div>
              </div>
            <?php endforeach; ?>
          <?php endif; ?>
        </div>
      </div>
    </section>
    <section class="w-full max-w-[400px] sticky top-8">
      <h2 class="text-xl font-bold mt-8 mb-4">Ajouter une classe</h2>
      <form
        action="<?= $this->baseUrl . "classes-sessions" ?>"
        method="POST"
        class="p-4 bg-white shadow rounded-lg border border-gray-300 flex flex-col gap-4">
        <input name="_method" type="hidden" value="post"></input>
        <!-- Nom Input -->
        <div>
          <label for="nom" class="block text-sm font-medium text-gray-700">Nom</label>
          <input type="text" id="nom" name="nom" class="p-3 border border-gray-300 mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500" required>
        </div>
        <!-- Submit Button -->
        <div>
          <button
            type="submit"
            class="w-full bg-gray-950 text-white py-2 px-4 rounded-md hover:bg-gray-800">Ajouter</button>
        </div>
      </form>
    </section>
  </div>
</div>

</body>

</html>