<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../public/main.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL" />
    <script src="https://kit.fontawesome.com/31465505a1.js" crossorigin="anonymous"></script>
    <!--tailwind-->
    <script src="https://cdn.tailwindcss.com"></script>
    <script>
        tailwind.config = {
            theme: {
                extend: {
                    colors: {
                        'beige': {
                            '50': '#f9f5f3',
                            '100': '#f3ebe5',
                            '200': '#e3d1c5',
                            '300': '#d2b29f',
                            '400': '#bf8e78',
                            '500': '#b1745e',
                            '600': '#a46252',
                            '700': '#894f45',
                            '800': '#6f423d',
                            '900': '#5b3733',
                            '950': '#301c1a',
                        },
                        'red': {
                            '50': '#fcf4f4',
                            '100': '#fae6e6',
                            '200': '#f3c5c5',
                            '300': '#eeb3b3',
                            '400': '#e38686',
                            '500': '#d45f5f',
                            '600': '#bf4343',
                            '700': '#a03535',
                            '800': '#852f2f',
                            '900': '#6f2d2d',
                            '950': '#3c1313',
                        },
                        'orange': {
                            '50': '#fef7ee',
                            '100': '#fcedd8',
                            '200': '#fae0c1',
                            '300': '#f4bb7d',
                            '400': '#ef9448',
                            '500': '#ea7825',
                            '600': '#dc5f1a',
                            '700': '#b64718',
                            '800': '#91391b',
                            '900': '#753119',
                            '950': '#3f160b',
                        },
                        'blue': {
                            '50': '#f4f3ff',
                            '100': '#ebe9fe',
                            '200': '#d5d2fe',
                            '300': '#bcb5fd',
                            '400': '#9b8bfa',
                            '500': '#7b5cf6',
                            '600': '#693aed',
                            '700': '#5a28d9',
                            '800': '#4b21b6',
                            '900': '#3f1d95',
                            '950': '#251065',
                        },
                        'cruise': {
                            '50': '#eefbf5',
                            '100': '#d5f6e6',
                            '200': '#bff0db',
                            '300': '#79dcb8',
                            '400': '#43c499',
                            '500': '#20a980',
                            '600': '#128968',
                            '700': '#0f6d55',
                            '800': '#0e5744',
                            '900': '#0d473a',
                            '950': '#062821',
                        },
                    }
                },
                borderRadius:{
                    'xsm':'5px',
                    'sm':'10px',
                    'md':'15px',
                    'lg':'20px'
                }
            }
        }
    </script>
    <!--tailwind-->
    <title>App doriane</title>
</head>